### ISSUE TITLE
The navigator closes unexpectedly

### ISSUE THREAD

**Issue by walkccc** [zalando-incubator/hexo-theme-doc#116]
## Expected Behavior
The navigator should expand when I click to a children of children .html page. For example, when I click to "Problem 2-1", the navigator should highlight "Problem 2-1" to orange, and keeps expanding the content in the navigator.

<img width="238" alt="expand" src="https://user-images.githubusercontent.com/14782909/35763637-839cadcc-08eb-11e8-976d-1a46806aa2dd.png">

## Actual Behavior
The navigator closes when I click to a children of children .html page.
After clicking "Problem 2-1", the navigator will close, which is not so convenient.
<img width="326" alt="close" src="https://user-images.githubusercontent.com/14782909/35763692-81a76394-08ec-11e8-83e9-7d07dd786cd8.png">

## Steps to Reproduce the Problem

The codes:

```
- text: 2 Getting Started
  type: link
  path: Chap02/2.0.html
  children:
  - text: 2.1 Insertion sort
    type: link
    path: Chap02/2.1.html
  - text: 2.2 Analyzing algorithms
    type: link
    path: Chap02/2.2.html
  - text: 2.3 Designing algorithms
    type: link
    path: Chap02/2.3.html
  - text: Chap 2. Problems
    type: link
    path: Chap02/2-0.html
    children:
    - text: Problem 2-1
      type: link
      path: Chap02/2-1.html
    - text: Problem 2-2
      type: link
      path: Chap02/2-2.html
    - text: Problem 2-3
      type: link
      path: Chap02/2-3.html
    - text: Problem 2-4
      type: link
      path: Chap02/2-4.html
```

## Specifications

  - NodeJS Version: 8.9.4
  - NPM Version: 5.6.0
  - OS: macOS High Sierra version 10.13.3
  - Hexo Version: 3.5.0

Btw, is it possible to change the default color orange to other colors(like lightblue or green)?
I've modified the directory you mentioned in the documentation [Hexo Doc Theme | SASS styles](https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/sass-styles.html), but it seems it's not so easy to change this?

Thanks a lot!
