### ISSUE TITLE
No menu item on sidebar (other than the title)

### ISSUE THREAD

**Issue by rama-adi** [zalando-incubator/hexo-theme-doc#134]
## Expected Behavior
Sidebar item showing up.

## Actual Behavior

Nothing. Just the title, i've tried the quick (seed) and long start (npm), same result.

## Steps to Reproduce the Problem

  1. Just copy the navigation from the docs.

## Specifications

  - NodeJS Version: 8.11.2
  - NPM Version: 5.6.0
  - OS: Windows 10
  - Hexo Version: 3.7.1

Thanks for helping!

**Comment by rbarilani** [comment]
Hi @Ramacraft123 can you post your `_data/navigation.yaml` file?

**Comment by Ramacraft123** [comment]
@rbarilani it's the default, i've not modified anything.
```yaml
{
  "logo": {
    "text": "Hexo Doc Theme Seed",
    "type": "link",
    "path": "index.html"
  },
  "main": [
    {
      "text": "SWAGGER",
      "type": "label"
    },
    {
      "text": "UI",
      "type": "link",
      "path": "swagger/ui.html"
    },
    {
      "text": "To HTML",
      "type": "link",
      "path": "swagger/to-html.html"
    },
    {
      "text": "SUPPORT AND FEEDBACK",
      "type": "label"
    },
    {
      "text": "Raise an Issue on Github",
      "type": "link",
      "path": "https://github.bus.zalan.do/stargate/hexo-stargate-doc-theme-seed/issues/new"
    }
  ]
}
```
