### ISSUE TITLE
navigation example?

### ISSUE THREAD

**Issue by wolfcon** [zalando-incubator/hexo-theme-doc#145]
[https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/navigation.html](https://zalando-incubator.github.io/hexo-theme-doc/usage-and-configuration/navigation.html)
How to write yaml like navigation.yaml. 

Could you post your navigation.yaml of this site. thx🙏

`#menu-1` and `children` could not be shown.

this is my navigation.yaml
```
logo:
  text: My Documentation
  type: link
  path: index.html

main:
- text: PROJECTS
  type: label
- text: 新媒体
  type: link
  path: Public guide/public guide
  children:
    - text: 1
       type: link
       path: Public guide/public guide#4-a
    - text: 2
       type: link
       path: Public guide/public guide#5-b
```
