### ISSUE TITLE
Cannot use layout variable or helper in project partial

### ISSUE THREAD

**Issue by whoiscc** [zalando-incubator/hexo-theme-doc#157]
## Expected Behavior
Use `url_for` in project partial.

## Actual Behavior
Not work. Error report:

```
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
ReferenceError: /Users/cowsay/Projects/fridge/source/layout/styles.ejs:2
    1| <link
 >> 2|   href="<%- url_for('katexify/katex.min.css') %>"
    3|   rel="stylesheet"
    4| />
    5| 

url_for is not defined
...
```

## Steps to Reproduce the Problem

  1. Add this to `_config.yml`

```yml
theme_config:
  favicon: images/logo.png
  partials:
    head_end:
      - ./layout/styles.ejs
```

  2. Add a file `source/layout/styles.ejs` with this content

```ejs
<link
  href="<%- url_for('katexify/katex.min.css') %>"
  rel="stylesheet"
/>
```

  3. `yarn hexo server`

## Specifications

  - NodeJS Version: 11.12.0
  - NPM Version: 6.7.0 (yarn 1.13.0)
  - OS: macOS 10.14
  - Hexo Version: 3.8.0

**Comment by rbarilani** [comment]
@whoiscc I tried an I am encountering the same problem but IMO us the hexo renderer trying to render that `ejs` file also if you don't specify it as project partial. try to comment out the project partial configuration.

```yaml
theme_config:
  favicon: images/logo.png
  # partials:
  # head_end:
  #   - ./layout/styles.ejs
```

It will trigger an error also if you are not using it as a project_partial.

As an easy fix  you can name the file `_styles.ejs` so Hexo it will not try to render it.

```yaml
theme_config:
  favicon: images/logo.png
  partials:
    head_end:
     - ./layout/_styles.ejs
```
