### ISSUE TITLE
Search input is not displayed

### ISSUE THREAD

**Issue by lnimong** [zalando-incubator/hexo-theme-doc#176]
## Expected Behavior
After my static site is generated I have a search input on the top left on my page

## Actual Behavior
After my static stite is generated I have no search input on the top left on my page

## Steps to Reproduce the Problem

(it's on a private repository for my company so I can't git you the repository)

my _config.yaml file
```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Offer Managment Doc
author: Vincent Miquel
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: /
root: "/sourcing/products/offermanagement/offer-management-docs/"

# Writing
relative_link: true

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-doc

theme_config:
  favicon: images/favicon.ico

ignore:
  # development only: ignore sub node_modules when `npm link hexo-theme-doc`
  - '**/node_modules/**/*node_modules'

```

  1. I go the root directory 
  2. I run ~# npm install
  3. I run ~# hexo generate
  4. the "public" directory is properly generated
  5. I serve the  public directory using (https://www.npmjs.com/package/serve) ~# serve ./public
  6. the static website is generated indeed
  7. Except there is an empty space instead of the search input 

## Specifications

  - NodeJS Version: 10.15.1
  - NPM Version: 6.4.1
  - OS: Windows 10 (Version	10.0.18362 Build 18362)
  - Hexo Version: 3.8.0
