### ISSUE TITLE
feat(layout): provide a way to load extra stylesheets and scripts

### ISSUE THREAD

**Issue by rbarilani** [zalando-incubator/hexo-theme-doc#25]
Provide a way to load extra stylesheets and scripts 

Proposal:

*_config.yml*
```yaml
theme_config:
   layout_blocks:
      head: 
          - stylesheet:my-custom.css
          - javascript:my-custom.js
     footer:
          - javascript:my-custom-2.js
```

Proposal 2:

Just give the possibility to add "partials" directly?

```yaml
theme_config:
   layout:
      head_start: partials/mobile-favicon.ejs # ./source/partials/mobile-favicon.ejs
      head_end: partials/include-custom-styles.ejs
      footer:
          - partials/include-custom-javascript.ejs
          - partials/copyright.ejs
```
